import Head from "next/head";
import styled from "styled-components";

const MainContainer = styled('div')`
  padding: 15px;
`
const H2 = styled("h2")`
  color: #ed6c54;
  font-weight: 700;
  text-align: justify;
  padding: 0px 100px;
  margin-top: 100px;
  font-style: italic;
  @media(max-width: 1200px) {
    margin: 0;
  }
  @media(max-width: 768px) {
    padding: 0px 15px;
  }
`;
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <H2>
          Technologies I work with
        </H2>
      </MainContainer>
    </>
  );
}
