import FilledCircle from "@/components/Elements/Geometric/FilledCircle";
import Triangle from "@/components/Elements/Geometric/Triangle";
import Cards from "@/components/pageBlocks/Cards";
import Head from "next/head";
import styled from "styled-components";

const Slider = styled("div")`
  display: flex;
  height: 500px;
  padding: 0px 15px;
  background-color: #222;
  position: relative;
`;
const MainContainer = styled('div')`
  padding: 15px;
`
const Text = styled("div")`
  display: flex;
  width: 50%;
  flex-direction: column;
  justify-content: center;
`;
const Photo = styled("div")`
  width: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
`;
const H4 = styled("h4")`
  color: #d8cfcf;
  font-weight: 700;
  text-align: justify;
  padding: 0px 100px;
  font-size: 18px;
`;
const H2 = styled("h2")`
  color: #ed6c54;
  font-weight: 700;
  text-align: justify;
  padding: 0px 100px;
  font-style: italic;
`;
const BackgroundPhoto = styled(FilledCircle)`
  width: 400px;
  height: 400px;
  left: 240px;
  background-color: #2f2f2f;
`;
const StyledTriangle = styled(Triangle)`
  bottom: 100%;
  top: 10px;
`;
const StyledCircule = styled(FilledCircle)`
  bottom: 100%;
  top: 90px;
  margin-left: 90px;
  &::before {
    background-color: #06F6B8;
  }
`;
const Name = styled('div')`
  position: absolute;
  left: 100px;
  top: 100px;
  color: #d8cfcf;
  font-size: 50px;
  font-weight: 800;
  z-index: 999;
`
const LastName = styled(Name)`
 top: 150px;
 left: 150px;
`
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider>
        <Name>
          Ronald
        </Name>
        <LastName>
          Lopez
        </LastName>
        <Photo>
          <BackgroundPhoto />
        </Photo>
        <Text>
          <StyledTriangle />
          <StyledCircule />
            <H2>FULL STACK DEVELOPER</H2>
          <H4>
            I&apos;m a skilled full stack web developer experienced in front-end
            and back-end technologies. I create responsive websites with
            user-centric designs and optimized performance. Let&apos;s bring
            your web project to life together!
          </H4>
        </Text>
      </Slider>
      <MainContainer>
        <H2>
          Technologies I work with
        </H2>
        <Cards />
      </MainContainer>
    </>
  );
}
